### ISSUE TITLE
X-RateLimit-Used

### ISSUE THREAD

**Issue by eyesuk** [alienbrett/PyAlly#25]
Is there a way that we can obtain the limit header information?
I am getting timeout errors and although I am almost sure I am staying way below the limits, I can't rule out if the crappy code I am writing is causing issues.

Is this possible

[Rate Limiting Info Here](https://www.ally.com/api/invest/documentation/rate-limiting/)

I am getting this error randomly
Exception has occurred: ReadTimeout
HTTPSConnectionPool(host='api.tradeking.com', port=443): Read timed out. (read timeout=3)

**Comment by JTraversa** [comment]
ReadTimeout could potentially be caused by their internal rate limitation blocking the call and not giving you the correct error but I believe is more often caused by an issue with their server not responding to your call in an acceptable timeframe.

Generally I just catch the exception, sleep for a second or two and try the api call again.

**Comment by alienbrett** [comment]
You'll know it returns a rate-limited error response if you receive a HTTP 429 error. In the future this can be made more explicit

**Comment by eyesuk** [comment]
Thanks guys! I hope you and your love ones are all safe.  I appreciate you guys
