### ISSUE TITLE
question related to logging in

### ISSUE THREAD

**Issue by jr751** [alienbrett/PyAlly#38]
Two questions.

1. Is it possible to place trades using the PyAlly module without first manually logging in to the Ally website? If so, how do you do this?

2. Is it possible to prevent being automatically logged out of the Ally invest website due to inactivity?

**Comment by alienbrett** [comment]
1. You need to log into the website to get your account api tokens for the first time- there's no way to get the tokens without first accessing the account page online.

2. Once you have the api tokens, you don't even need to log in again unless you want to change or invalidate the keys. If you're talking about preventing the page from reloading while you're using it normally for trading, then the answer is no. Usually banks' websites log out automatically after some set period of time in order to prevent unauthorized access if someone gets a hold of the computer. They usually take conservative measures like this that might seem annoying, but in order to minimize security issues.
